name: Release App

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-tauri:
    permissions:
      contents: write
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend deps
        run: npm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__
          releaseName: 'Family Weaver v__VERSION__'
          releaseBody: |
            # Family Weaver v__VERSION__

            ## What's new
            - When creating a new person, the "relationship" tab has been redesigned to support finding the right parents/children/partners more easily and quicker - Including a quick search for names and "suggested" people that seem most logical.
            - When using the calendar to pick a date, the year had to be typed or manually increased/decreased one year at a time. This has been changed to allow you to select a year quicker without the need to type in a year.
            - To avoid accidentally creating a new person without connecting any relationships, a warning will appear when saving a person without any relationships.
            - Added "gender" to the "overview" section of creating a person.

            ## Under the Hood
            - Fixed a bug where deleting the last/only tree wouldn't correctly delete and continue to show the same tree.
            - People are no longer shared between trees as this was a bug. Each tree now has their own set of people that aren't shared between other trees.
            - When saving a person to your tree, the next time you go to create a new person, it will default to opening on the "overview" section.
            - A bug was fixed where the daate picker calendar would default to light mode when settings was set to "system" with no detection for whether "system" was in light or dark mode.
            - When there is nobody available to add as a relationship, the "add relationship" button will be disabled to avoid confusion.
            - Made the `remove` button on the "relationship" tab after adding one or more relationships more clear that it is for removing the relationship and not the person.
            - Fixed a bug where the tree visual wasn't updated correctly when the last tree was deleted.
          releaseDraft: false
          prerelease: false