name: Release App

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-tauri:
    permissions:
      contents: write
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend deps
        run: npm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__
          releaseName: 'Family Weaver v__VERSION__'
          releaseBody: |
            # Family Weaver v__VERSION__

            ## What's new
                - Added confirmation notifications. When you create a person, save changes, or perform other actions, you'll now see a quick message in the bottom right corner confirming it worked (or letting you know if there was an issue).
                - When choosing "later" for an update, there will be an option to update the app without needing to restart it to get the update. This update option can be seen in the "app" menu in the toolbar **only** when there is an update available.
                - The app automatically checks for updates every 2 hours (by default).
                - Implemented Settings, focusing on accessability, which can be accessed from the "app" menu in the toolbar.
                - The animated tree at app open (when check updates is enabled) is faster, smoother, more efficient and it completes it's whole animation - rather than before where it often wouldn't reach the end of the animation before the app was ready to use.'
                - The `Create family tree" modal's title was the same size as all other text -> made this bigger as it was supposed to be.
                - The tree loading at the start (if enabled) is improved for better performance.
                - The tree loading at the start (if enabled) doesn't render leaves in winter time.
            ## Under the Hood
                - Fixed the markdown in "What's new" modal where it wasn't rendering bullet points.
                - Fixed `CreateTree`, `SwitchTreeModal` & `RenameTreeTitle` as they was managing local close states which wasn't allowing them to close at all.
                - Changed the "upload" tab in create person modal to "media".
                - Changed "Settings" in the toolbar to "app" to better fit the content it can include.
                - Decreased the memory used by the app by a tiny amount, resulting in very slightly better performance.
                - Squashed lots of minor small bugs.
          releaseDraft: false
          prerelease: false